# Site settings
title: "workshop"
email: rishabhad93@gmail.com
description: "hashroot's showcase."
baseurl: ""
url: "hashroot.github.io/"
title_description: "I'm rishabh dubey. Android Freak | Blogger | Freelancer | Tech Addict | ♥ Gadgets"
title_image: "https://avatars0.githubusercontent.com/u/2835893?v=3&s=460"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/hashroot/hashroot.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: ihashroot
github_username:  hashroot
#linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/hashroot/hashroot.github.com\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
 redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
